<?php

/**
 * @file
 * Contains code to refill escape button caches when cache has been cleared.
 */

use Drupal\Core\Site\Settings;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use GuzzleHttp\Client;

/**
 * Rebuild data based upon refreshed caches.
 *
 * This hook retrieved the escape button module history pages
 * so that they are stored in cache and ready to use immediately
 * when the exit button is used.
 */
function bhcc_escape_button_rebuild() {

  $historyItems = [];
  $host = '';

  // Get the configured uri - if not set, use http scheme and host value.
  $host = Settings::get('bhcc_host_uri') ?? \Drupal::request()->getSchemeAndHttpHost();

  // If not uri is provided (e.g. when drush cr used on commandline), exit.
  if ($host == 'http://default') {
    \Drupal::logger('bhcc_escape_button')->warning("The requested domain ('$host') cannot be preloaded");
    return FALSE;
  }

  // Check the home page is available - if not exit.
  try {
    $client = new Client();
    $client->get($host);
  }
  catch (Exception $e) {
    \Drupal::logger('bhcc_escape_button')->warning("The requested domain (' . $host .  ') is not available:- " . $e->getMessage());
    return FALSE;
  }

  // Get the list of history items.
  $entity_type_manager = \Drupal::entityTypeManager();
  $escape_buttons = $entity_type_manager->getStorage('block')->loadByProperties([
    'plugin' => 'escape_button_block',
  ]);

  foreach ($escape_buttons as $escape_button) {

    if ($escape_button) {
      $settings = $escape_button->get('settings');
      $historyItems = $settings['history'];
    }

    if (empty($historyItems)) {
      \Drupal::logger('bhcc_escape_button')->warning('There are no history items to use when preloading cache');
      return FALSE;
    }

    // Cycle through and request to get them cached.
    foreach ($historyItems as $historyNodeID) {
      Node::load($historyNodeID);
      try {
        $client = new Client();
        $current_url = Url::fromRoute('entity.node.canonical', ['node' => $historyNodeID], ['absolute' => FALSE])->toString();
        $client->get($host . $current_url);
        \Drupal::logger('bhcc_escape_button')->notice('Cache refreshed for node = ' . $historyNodeID);
      }
      catch (Exception $e) {
        \Drupal::logger('bhcc_escape_button')->warning('node:=' . $historyNodeID . ', ' . $e->getMessage());
      }
    }
  }
}
